services:
  - type: web
    name: cogniscent-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m textblob.download_corpora
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
